repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        entry: uv run ruff check --fix
        types: [python]
      - id: ruff-format
        name: ruff-format
        language: system
        entry: uv run ruff format
        types: [python]
