# MVP parameters
EMBEDDING_DIM = 10  # k
PROJECTION_OUTPUT_DIM = 1  # m
N_INTERIOR_KNOTS = 5  # K
SPLINE_DEGREE = 3  # d

# Other constants
N_RECORDINGS = 100
RECORDING_DURATION_MIN = 10
SEC_IN_MIN = 60
FS = 128
N_TIME_STEPS = RECORDING_DURATION_MIN * SEC_IN_MIN * FS
UV_SCALING_FACTOR = 200  # EEG time series roughly on the order 200 uV
N_ITER_REPRODUCIBILITY = 100
